/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LandpageCodeRouteImport } from './routes/landpage.$code'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPesquisasRouteImport } from './routes/_app.pesquisas'
import { Route as AppLiderancasRouteImport } from './routes/_app.liderancas'
import { Route as AppEquipeRouteImport } from './routes/_app.equipe'
import { Route as AppEleitoresRouteImport } from './routes/_app.eleitores'
import { Route as AppDemandasRouteImport } from './routes/_app.demandas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminTenantsRouteImport } from './routes/_admin.tenants'
import { Route as AdminPlansRouteImport } from './routes/_admin.plans'
import { Route as AdminMetricasRouteImport } from './routes/_admin.metricas'
import { Route as AppEquipeIndexRouteImport } from './routes/_app.equipe.index'
import { Route as AppEquipeCargosRouteImport } from './routes/_app.equipe.cargos'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LandpageCodeRoute = LandpageCodeRouteImport.update({
  id: '/landpage/$code',
  path: '/landpage/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPesquisasRoute = AppPesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => AppRoute,
} as any)
const AppLiderancasRoute = AppLiderancasRouteImport.update({
  id: '/liderancas',
  path: '/liderancas',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppEleitoresRoute = AppEleitoresRouteImport.update({
  id: '/eleitores',
  path: '/eleitores',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandasRoute = AppDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminRoute,
} as any)
const AppEquipeIndexRoute = AppEquipeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEquipeRoute,
} as any)
const AppEquipeCargosRoute = AppEquipeCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AppEquipeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/metricas': typeof AdminMetricasRoute
  '/plans': typeof AdminPlansRoute
  '/tenants': typeof AdminTenantsRoute
  '/users': typeof AdminUsersRoute
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/demandas': typeof AppDemandasRoute
  '/eleitores': typeof AppEleitoresRoute
  '/equipe': typeof AppEquipeRouteWithChildren
  '/liderancas': typeof AppLiderancasRoute
  '/pesquisas': typeof AppPesquisasRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/landpage/$code': typeof LandpageCodeRoute
  '/p/$slug': typeof PSlugRoute
  '/equipe/cargos': typeof AppEquipeCargosRoute
  '/equipe/': typeof AppEquipeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/metricas': typeof AdminMetricasRoute
  '/plans': typeof AdminPlansRoute
  '/tenants': typeof AdminTenantsRoute
  '/users': typeof AdminUsersRoute
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/demandas': typeof AppDemandasRoute
  '/eleitores': typeof AppEleitoresRoute
  '/liderancas': typeof AppLiderancasRoute
  '/pesquisas': typeof AppPesquisasRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/landpage/$code': typeof LandpageCodeRoute
  '/p/$slug': typeof PSlugRoute
  '/equipe/cargos': typeof AppEquipeCargosRoute
  '/equipe': typeof AppEquipeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_admin/metricas': typeof AdminMetricasRoute
  '/_admin/plans': typeof AdminPlansRoute
  '/_admin/tenants': typeof AdminTenantsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/demandas': typeof AppDemandasRoute
  '/_app/eleitores': typeof AppEleitoresRoute
  '/_app/equipe': typeof AppEquipeRouteWithChildren
  '/_app/liderancas': typeof AppLiderancasRoute
  '/_app/pesquisas': typeof AppPesquisasRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/landpage/$code': typeof LandpageCodeRoute
  '/p/$slug': typeof PSlugRoute
  '/_app/equipe/cargos': typeof AppEquipeCargosRoute
  '/_app/equipe/': typeof AppEquipeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/metricas'
    | '/plans'
    | '/tenants'
    | '/users'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/demandas'
    | '/eleitores'
    | '/equipe'
    | '/liderancas'
    | '/pesquisas'
    | '/relatorios'
    | '/auth/callback'
    | '/invite/$token'
    | '/landpage/$code'
    | '/p/$slug'
    | '/equipe/cargos'
    | '/equipe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/metricas'
    | '/plans'
    | '/tenants'
    | '/users'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/demandas'
    | '/eleitores'
    | '/liderancas'
    | '/pesquisas'
    | '/relatorios'
    | '/auth/callback'
    | '/invite/$token'
    | '/landpage/$code'
    | '/p/$slug'
    | '/equipe/cargos'
    | '/equipe'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_admin/metricas'
    | '/_admin/plans'
    | '/_admin/tenants'
    | '/_admin/users'
    | '/_app/agenda'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/demandas'
    | '/_app/eleitores'
    | '/_app/equipe'
    | '/_app/liderancas'
    | '/_app/pesquisas'
    | '/_app/relatorios'
    | '/auth/callback'
    | '/invite/$token'
    | '/landpage/$code'
    | '/p/$slug'
    | '/_app/equipe/cargos'
    | '/_app/equipe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LandpageCodeRoute: typeof LandpageCodeRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landpage/$code': {
      id: '/landpage/$code'
      path: '/landpage/$code'
      fullPath: '/landpage/$code'
      preLoaderRoute: typeof LandpageCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesquisas': {
      id: '/_app/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof AppPesquisasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liderancas': {
      id: '/_app/liderancas'
      path: '/liderancas'
      fullPath: '/liderancas'
      preLoaderRoute: typeof AppLiderancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eleitores': {
      id: '/_app/eleitores'
      path: '/eleitores'
      fullPath: '/eleitores'
      preLoaderRoute: typeof AppEleitoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demandas': {
      id: '/_app/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AppDemandasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenants': {
      id: '/_admin/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/plans': {
      id: '/_admin/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/metricas': {
      id: '/_admin/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/equipe/': {
      id: '/_app/equipe/'
      path: '/'
      fullPath: '/equipe/'
      preLoaderRoute: typeof AppEquipeIndexRouteImport
      parentRoute: typeof AppEquipeRoute
    }
    '/_app/equipe/cargos': {
      id: '/_app/equipe/cargos'
      path: '/cargos'
      fullPath: '/equipe/cargos'
      preLoaderRoute: typeof AppEquipeCargosRouteImport
      parentRoute: typeof AppEquipeRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMetricasRoute: AdminMetricasRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppEquipeRouteChildren {
  AppEquipeCargosRoute: typeof AppEquipeCargosRoute
  AppEquipeIndexRoute: typeof AppEquipeIndexRoute
}

const AppEquipeRouteChildren: AppEquipeRouteChildren = {
  AppEquipeCargosRoute: AppEquipeCargosRoute,
  AppEquipeIndexRoute: AppEquipeIndexRoute,
}

const AppEquipeRouteWithChildren = AppEquipeRoute._addFileChildren(
  AppEquipeRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDemandasRoute: typeof AppDemandasRoute
  AppEleitoresRoute: typeof AppEleitoresRoute
  AppEquipeRoute: typeof AppEquipeRouteWithChildren
  AppLiderancasRoute: typeof AppLiderancasRoute
  AppPesquisasRoute: typeof AppPesquisasRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDemandasRoute: AppDemandasRoute,
  AppEleitoresRoute: AppEleitoresRoute,
  AppEquipeRoute: AppEquipeRouteWithChildren,
  AppLiderancasRoute: AppLiderancasRoute,
  AppPesquisasRoute: AppPesquisasRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
  LandpageCodeRoute: LandpageCodeRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
