/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPesquisasRouteImport } from './routes/_app.pesquisas'
import { Route as AppLiderancasRouteImport } from './routes/_app.liderancas'
import { Route as AppEleitoresRouteImport } from './routes/_app.eleitores'
import { Route as AppDemandasRouteImport } from './routes/_app.demandas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPesquisasRoute = AppPesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => AppRoute,
} as any)
const AppLiderancasRoute = AppLiderancasRouteImport.update({
  id: '/liderancas',
  path: '/liderancas',
  getParentRoute: () => AppRoute,
} as any)
const AppEleitoresRoute = AppEleitoresRouteImport.update({
  id: '/eleitores',
  path: '/eleitores',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandasRoute = AppDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/demandas': typeof AppDemandasRoute
  '/eleitores': typeof AppEleitoresRoute
  '/liderancas': typeof AppLiderancasRoute
  '/pesquisas': typeof AppPesquisasRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AppAgendaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/demandas': typeof AppDemandasRoute
  '/eleitores': typeof AppEleitoresRoute
  '/liderancas': typeof AppLiderancasRoute
  '/pesquisas': typeof AppPesquisasRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/demandas': typeof AppDemandasRoute
  '/_app/eleitores': typeof AppEleitoresRoute
  '/_app/liderancas': typeof AppLiderancasRoute
  '/_app/pesquisas': typeof AppPesquisasRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/demandas'
    | '/eleitores'
    | '/liderancas'
    | '/pesquisas'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/demandas'
    | '/eleitores'
    | '/liderancas'
    | '/pesquisas'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/agenda'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/demandas'
    | '/_app/eleitores'
    | '/_app/liderancas'
    | '/_app/pesquisas'
    | '/_app/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pesquisas': {
      id: '/_app/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof AppPesquisasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liderancas': {
      id: '/_app/liderancas'
      path: '/liderancas'
      fullPath: '/liderancas'
      preLoaderRoute: typeof AppLiderancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eleitores': {
      id: '/_app/eleitores'
      path: '/eleitores'
      fullPath: '/eleitores'
      preLoaderRoute: typeof AppEleitoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demandas': {
      id: '/_app/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AppDemandasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDemandasRoute: typeof AppDemandasRoute
  AppEleitoresRoute: typeof AppEleitoresRoute
  AppLiderancasRoute: typeof AppLiderancasRoute
  AppPesquisasRoute: typeof AppPesquisasRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDemandasRoute: AppDemandasRoute,
  AppEleitoresRoute: AppEleitoresRoute,
  AppLiderancasRoute: AppLiderancasRoute,
  AppPesquisasRoute: AppPesquisasRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
